### ISSUE TITLE
关于 createRender 中相关问题

### ISSUE THREAD

**Issue by Onlylonger** [lixinliang/bubble-hearts#1]
1. zoomInStage 和  zoomInRest 变量具体作用
2. getScale 方法中 (1 - lifespan) / zoomInRest) 是什么意思哦
3. amplitude 变量 代表的意思以及当中的 图像斜边 / 2 是什么意思哦

看了下源码不太明白，望能帮助下小弟-_-
@lixinliang

**Comment by lixinliang** [comment]
# Q1

```js
const zoomInStage = random.uniformDiscrete(89, 91) / 100
const zoomInRest = 1 - zoomInStage
```
从源码上看，`zoomInStage` 是一个 随机 0.89~0.91 的随机值
`zoomInRest` 是剩余(rest)的部分

`zoomInStage` 里面的 `stage` 是指达到某个阶段
假设随机值是 0.9
那么 1~0.9 的阶段是 zoom-in 的过程
动画元素会逐渐放大
`zoomInRest` 是剩余部分
那么剩余的部分需要做其他操作
避免在每个函数都计算一遍故而用变量保存

> 因为 动画寿命 lifespan 是从 1 递减到 0

---

```js
  let getTranslateX = (lifespan) => {
    if (lifespan > zoomInStage) {
      return basicTranslateX
    } else {
      return basicTranslateX + wave * Math.sin(frequency * (zoomInStage - lifespan) * Math.PI / 180)
    }
  }
```
`zoomInStage` 在 `getTranslateX` 上用到
这个方法根据 当前单个动画元素寿命 `lifespan` 返回不同的 `x` 坐标

`lifespan` 大于 `zoomInStage` 的时候返回一个固定 `x` 坐标
动画就会垂直向上 (因为 `y` 坐标是递增的) 这时候动画刚开始 

`lifespan` 小于 `zoomInStage` 的时候返回一个关联 `lifespan` 的 `x` 坐标
动画就会左右飘动

---

```js
  let getScale = (lifespan) => {
    if (lifespan > zoomInStage) {
      return Math.max(((1 - lifespan) / zoomInRest).toFixed(2), 0.1) * basicScale
    } else {
      return basicScale
    }
  }
```
`zoomInRest` 在 `getScale` 上用到
这个方法根据 当前单个动画元素寿命 `lifespan` 返回不同的 `scale` 缩放率

`lifespan` 大于 `zoomInStage` 的时候返回一个关联 `lifespan` 的缩放率
动画就会垂直向上的同时放大 (因为 `y` 坐标是递增的) 这时候动画刚开始 

`lifespan` 小于 `zoomInStage` 的时候返回一个固定的缩放率
动画不再放大仅仅左右飘动

**Comment by lixinliang** [comment]
# Q2

`zoomInRest` 避免在每个函数都计算一遍故而用变量保存

```js
(1 - lifespan) / zoomInRest)
```
一个关联 lifespan 的缩放率公式

`zoomInStage` 是随机生成的
假设是 `zoomInStage` 是 0.9
那么  lifespan 递减的过程中 1~0.9 是动画放大的阶段
`(1 - lifespan) / (1 - 0.9)` 是计算当前阶段的百分比
假设 lifespan 是 0.95
则得到当前动画放大阶段已经达到到 50%
故而 `zoomInRest = 1 - 0.9`

**Comment by lixinliang** [comment]
# Q3

```
const amplitude = (canvas.width - Math.sqrt(Math.pow(image.width, 2) + Math.pow(image.height, 2))) / 2 - offset
```

(整个动画画布的宽度 - 平方根( 图片宽度平方 + 图片高度平方 )) 除2 减 offset

### 为什么要求图片的斜边 (宽度高度平方和再平方根)?
因为整个动画会操作图片放大旋转
考虑最大旋转 45° 的情况下 该图片在 画布上的 宽度投影的 距离就是 斜边的距离

### 这个公式的目的
因为图片旋转 45° 后左右飘动 会超出画布的边缘 导致裁切
所以需要求一个 安全区间

### 这个公式的思路
假设这个图片初始位置在画布中间
那么 画布宽度 减去 图片的最大宽度 除2 后
就是这个图片可以左右飘动的最大距离

### 固定参数 offset
因为图片的初始位置不是在画布中间
会根据 offset 有一个浮动值 最大仅可能是 offset
左右飘动的安全距离 amplitude 再减去 offset 确保空间足够安全 避免图片被裁切
